# Coding Assignment 2

# Problem Statement

Let the matrix be [[2,1,0] [1,3,-1] [0,-1,4]]

Write a piece of code to calculate the eigenvalue and eigenvector of matrix A. You may use Python functions to do calculate them. How can you verify that the eigenvectors that correspond to distinct eigenvalues are independent? Is there a way to code it in Python? Clue : Reduced Row Echelon.

Solution:

    1.Find the Eigenvalues and Eigenvectors of the given matrix.
    2.
        a)If we get distinct eigen values,we have to prove that the eigenvectors that corresponds to that eigenvalues are independent vectors.For that ,we have to use Reduced Row Echolon Form (RREF),In that if the number of pivot columns matches the number of distinct eigenvalues, it suggests that the eigenvectors corresponding to distinct eigenvalues are independent.
        b)Otherwise linearly dependent

In [2]:
# install numPy and sumPy libraries using pip command by running cmd in the administer mode
# import numpy and sumpy libraries
import numpy as np
import sympy

# declare and initialize the matrix
given_matrix = np.array([[2, 1, 0], [1, 3, -1],[0, -1, 4]])

# find eigenvalues and eigenvectors using np.linalg.eig() 
eigenvalues, eigenvectors = np.linalg.eig(given_matrix)

# display the eigenvalues and the eigenvectors found
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

# Check whether any eigenvalue is repeated(i.e check whether the eigen value is distinct or not)
distinct_eigenvalues = np.unique(eigenvalues)
if len(distinct_eigenvalues) != len(eigenvalues):
    print("Eigenvalues are not distinct.")
else:
    print("Eigenvalues are distinct.")

# Form matrix with eigenvectors corresponding to distinct eigenvalues
eigenvectors_matrix = np.column_stack([eigenvectors[:,i] for i in range(len(eigenvalues))])

# Convert matrix to RREF
# in order to find the reduced row element form(rref) directly we use symPy library,as we dont have any direct methods in numPy
# first convert numpy.array to sympy.matrix and then use rref() of symPy library 
rref_matrix, pivot_columns = sympy.Matrix(eigenvectors_matrix).rref()

# Check if the number of pivot columns matches the number of distinct eigenvalues
# if yes->independent else->dependent
if len(pivot_columns) == len(distinct_eigenvalues):
        print("Eigenvectors corresponding to distinct eigenvalues are independent.")
    else:
        print("Eigenvectors corresponding to distinct eigenvalues are dependent.")

Eigenvalues:
[1.26794919 3.         4.73205081]

Eigenvectors:
[[-0.78867513 -0.57735027 -0.21132487]
 [ 0.57735027 -0.57735027 -0.57735027]
 [ 0.21132487 -0.57735027  0.78867513]]
Eigenvalues are distinct.
Eigenvectors corresponding to distinct eigenvalues are independent.
